//
//  LearnKitError.swift
//  My Brighton
//
//  Created by Neo Salmon on 12/10/2025.
//

/// Represents a list of errors that can be throw by the service directly.
///  
/// This does not include errors thrown by internal frameworks such as SwiftData.
public enum LearnKitError: Error {
    case rootNodeMissing
    /// Represents an error generated by the LearnInstance.
    ///
    /// - Parameter error: Error generated by the Learn REST API.
    case restError(_ error: RestError)
    /// Represents an error raised by the service when trying to convert a remote object into a known model.
    ///
    /// Can commonly occur when:
    /// - The return status from the server is OK but the response body is not JSON
    /// - The remote object is missing required fields for model initialisation
    case cannotParseRemoteSchema
    /// Represents unknown errors encountered by the service.
    ///
    /// - Parameter statusCode: Status code for the error, if one is available.
    case unknown(statusCode: Int?)
}
